In [1]:
import pandas as pd
df = pd.read_csv(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,1419,Beautiful home in amazing area!,1565,Alexandra,NaN,Little Portugal,43.646170,-79.424510,Entire home/apt,469,4,7,4/12/2017,0.11,1,0
1,8077,Downtown Harbourfront Private Room,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.641050,-79.376280,Private room,99,180,169,27/08/2013,1.25,2,365
2,12604,Seaton Village Parlour Bedroom,48239,Rona,NaN,Annex,43.667240,-79.415980,Private room,66,1,0,NaN,NaN,1,0
3,23691,Queen Bedroom close to downtown,93825,Yohan & Sarah,NaN,Briar Hill-Belgravia,43.696020,-79.454680,Private room,70,1,217,22/12/2019,1.73,2,209
4,26654,World Class downtown @CN Tower Theatre MTCC ga...,113345,Adela,NaN,Waterfront Communities-The Island,43.645300,-79.389400,Entire home/apt,135,21,40,20/03/2020,0.34,5,216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19338,45348297,Studio Condo in Downtown Toronto #5,342316738,Davar,NaN,Church-Yonge Corridor,43.649440,-79.376090,Private room,99,30,0,NaN,NaN,24,264
19339,45351124,budget friendly nice place,342346982,Edip,NaN,Mount Pleasant West,43.699408,-79.390239,Shared room,37,1,0,NaN,NaN,7,365
19340,45351175,"affordable, long term place :)",342346982,Edip,NaN,Yonge-St.Clair,43.693933,-79.397942,Shared room,29,1,0,NaN,NaN,7,364
19341,45351235,Studio Unit with a nice view :),342346982,Edip,NaN,Yonge-Eglinton,43.706643,-79.401303,Entire home/apt,111,1,0,NaN,NaN,7,365
19342,45351322,Luxury Studio Condo Amazing LakeView,38189462,Frankie,NaN,Waterfront Communities-The Island,43.642040,-79.383045,Entire home/apt,111,2,0,NaN,NaN,3,22

In [ ]:
import pandas as pd
import numpy as np

df1 = (pd.read_csv(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
          .rename(columns={"id": "Property_id"})
          .rename(columns={"name": "Property_name"})
          .reset_index(drop=True) )
df2 = (
            df1
            .sort_values("price", ascending=True)
            .drop(columns=['neighbourhood_group'])
            .drop(columns=['longitude', 'latitude'])
            .dropna()
     
           )
df2


    # Make sure to return the latest dataframe

In [5]:
from Scripts import poject # This is called a relative import
df = poject.load_and_process(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
df.head()

,Property_id,Property_name,host_id,host_name,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,1419,Beautiful home in amazing area!,1565,Alexandra,Little Portugal,Entire home/apt,469,4,7,4/12/2017,0.11,1,0
1,8077,Downtown Harbourfront Private Room,22795,Kathie & Larry,Waterfront Communities-The Island,Private room,99,180,169,27/08/2013,1.25,2,365
3,23691,Queen Bedroom close to downtown,93825,Yohan & Sarah,Briar Hill-Belgravia,Private room,70,1,217,22/12/2019,1.73,2,209
4,26654,World Class downtown @CN Tower Theatre MTCC ga...,113345,Adela,Waterfront Communities-The Island,Entire home/apt,135,21,40,20/03/2020,0.34,5,216
5,27423,Executive Studio Unit- Ideal for One Person,118124,Brent,Greenwood-Coxwell,Entire home/apt,54,120,26,30/08/2011,0.21,1,0

In [8]:
import pandas as pd
import numpy as np

df1 = (pd.read_csv(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
       .rename(columns={"id": "Property_id"})
       .rename(columns={"name": "Property_name"})
       .reset_index(drop=True) 
       .sort_values("price", ascending=True)
       .drop(columns=['neighbourhood_group'])
       .drop(columns=['longitude', 'latitude'])
       .dropna()
      )
df1
            
            
           

    # Make sure to return the latest dataframe

,Property_id,Property_name,host_id,host_name,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
17631,43036342,"Modern Suite + Free Parking, atop Union Station",13569432,Bremner Suites,Waterfront Communities-The Island,Entire home/apt,12,28,3,23/08/2020,0.71,1,109
5928,19242082,"Peaceful home, right by subway station (401, 404)",134722504,Kivork,Don Valley Village,Shared room,13,7,3,14/11/2017,0.08,3,0
4784,16100281,"Futon/Couch in Davisville, Toronto",8001562,Diane,Yonge-St.Clair,Shared room,13,1,11,21/04/2017,0.24,2,0
11931,32901058,Cozy bunkbed in a warm and charming bedroom,152088065,Gennadi,Malvern,Shared room,14,1,3,24/10/2019,0.16,53,345
16951,42017267,Comfy bunkbed in a cozy shared room near TTC,152088065,Gennadi,Malvern,Shared room,14,1,4,30/06/2020,0.54,53,344
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8110,23416911,"Luxury Loft, in the heart of downtown Toronto",174625477,Angelo And Andre,Waterfront Communities-The Island,Entire home/apt,6848,30,28,21/02/2020,0.93,1,0
15918,40311257,Awesome loft in centre of Toronto,28076332,Denise,Bay Street Corridor,Entire home/apt,7155,1,3,13/01/2020,0.35,1,89
16289,40845163,Heart of Downtown Toronto & Amazing Lake View,317894650,Ana,Waterfront Communities-The Island,Entire home/apt,9999,28,10,14/03/2020,1.15,1,34
10136,28615622,Amazing furnished clean home Free parking + Wifi,215966560,Rooz,Newtonbrook West,Entire home/apt,13000,365,3,3/08/2019,0.13,1,0
6659,20653172,Modern Upscale Condo in downtown Toronto,147240941,Al,Waterfront Communities-The Island,Entire home/apt,13000,2,4,1/10/2017,0.11,2,0

In [21]:
from Scripts import cold 
df = cold.load_and_process(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
df

In [22]:
from Scripts import bold
df = bold.load_and_process(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
df

AttributeError: module 'Scripts.bold' has no attribute 'load_and_process'

In [20]:
from Scripts import bold 
df = bold.load_and_process(r'\Users\john\Desktop\course-project-solo_318-1\Analysis\listings(2).csv')
df

AttributeError: module 'Scripts.bold' has no attribute 'load_and_process'